name: Go

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: go list
        run: GOPROXY=proxy.golang.org go list -m github.com/loveholidays/go-config-loader@${{ github.ref_name }}
